version: '3.9'

services:
  db:
    image: mariadb:10
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=socialtale
      - MARIADB_DATABASE=socialtale
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      - MAILDEV_INCOMING_USER=admin
      - MAILDEV_INCOMING_PASS=secretpassword
